import { Sticker } from './sticker-book.state';

export const STICKER_BOOK_DATA: Sticker[] = [
  {id: 1, name:'5 Things Angular', fileName:'5-things-angular.svg' },
  {id: 2, name:'Angular 404', fileName:'angular-404.svg' },
  {id: 3, name:'Angular Academy', fileName:'angular-academy.svg' },
  {id: 4, name:'Angular Connect', fileName:'angular-connect.svg' },
  {id: 5, name:'Angular Dart', fileName:'angular-dart.svg' },
  {id: 6, name:'Angular Electron', fileName:'angular-electron.svg' },
  {id: 7, name:'Angular Firebase', fileName:'angular-firebase.svg' },
  {id: 8, name:'Angular Formly', fileName:'angular-formly.svg' },
  {id: 9, name:'Angular Hamburg', fileName:'angular-hamburg.svg' },
  {id: 10, name:'Angular Hightlight', fileName:'angular-highlight.svg' },
  {id: 11, name:'Angular Medellin Dark', fileName:'angular-medellin-dark.svg' },
  {id: 12, name:'Angular Meteor', fileName:'angular-meteor.svg' },
  {id: 13, name:'Angular NYC', fileName:'angular-nyc.svg' },
  {id: 14, name:'Angular Pakistan', fileName:'angular-pakistan.svg' },
  {id: 15, name:'Angular Swiss', fileName:'angular-swiss.svg' },
  {id: 16, name:'Angular Teximate', fileName:'angular-teximate.svg' },
  {id: 17, name:'Angular Toulouse', fileName:'angular-toulouse.svg' },
  {id: 18, name:'Angular Universal', fileName:'angular-universal.svg' },
  {id: 19, name:'Coldelyzer', fileName:'codelyzer.svg' },
  {id: 20, name:'Covalent', fileName:'covalent.svg' },
  {id: 21, name:'Nativescript Angular', fileName:'nativescript-angular.svg' },
  {id: 22, name:'NG-Atlanta', fileName:'ng-atlanta.svg' },
  {id: 23, name:'NG-Baires', fileName:'ng-baires.svg' },
  {id: 24, name:'NG-BE', fileName:'ng-be.svg' },
  {id: 25, name:'NG-Bootstrap', fileName:'ng-bootstrap.svg' },
  {id: 26, name:'NG-Conf 2015', fileName:'ng-conf-2015.svg' },
  {id: 27, name:'NG-Conf 2016', fileName:'ng-conf-2016.svg' },
  {id: 28, name:'NG-Conf 2017', fileName:'ng-conf-2017.svg' },
  {id: 29, name:'NG-Copenhagen', fileName:'ng-copenhagen.svg' },
  {id: 30, name:'NG-Europe', fileName:'ng-europe.svg' },
  {id: 31, name:'NG-Girls', fileName:'ng-girls.svg' },
  {id: 32, name:'NG-Lightning', fileName:'ng-lightning.svg' },
  {id: 33, name:'NG-Norway', fileName:'ng-norway.svg' },
  {id: 34, name:'NG-Vikings', fileName:'ng-vikings.svg' },
  {id: 35, name:'NG-Zorro', fileName:'ng-zorro.svg' },
  {id: 36, name:'ngRev', fileName:'ngrev.svg' },
  {id: 37, name:'NGRX', fileName:'ngrx.svg' },
  {id: 38, name:'NGX Bar Rating', fileName:'ngx-bar-rating.svg' },
  {id: 39, name:'NGX Cookie Consent', fileName:'ngx-cookie-consent.svg' },
  {id: 40, name:'NGX Disqus', fileName:'ngx-disqus.svg' },
  {id: 41, name:'NGX Wordpress', fileName:'ngx-wordpress.svg' },
  {id: 42, name:'Prime NG', fileName:'prime-ng.svg' },
  {id: 43, name:'Ultimate Angular', fileName:'ultimate-angular.svg' }
];
